#server
server:
  port: 8005
###################  自定义项目配置  ###################
yafjxz:
  file-server-url: http://59.46.113.245:8088/upload/
  vue-server-url: http://59.46.113.245:8088/
  save-path: /data//test//upload//   #预案上传保存位置 http://59.46.113.245:8088
  zip-path: /data//test//upload//    #压缩文件存放路径
  ################转换历史预案   http://localhost:8005/zhyafj/down
  ip-port: http://10.119.119.232:11010 #一体化文件系统地址 辽宁
  #ip-port: http://10.119.119.205:11010 #一体化文件系统地址 江苏
  #ip-port: http://192.168.1.105:11010 #一体化文件系统地址 西藏
  action: /attachment/filemanage/configFile!showFile.action #一体化文件系统方法
  max-size: 100  #单线程最大处理数据量
  base-dir: H://ya/ #基础路径
#------------------------------------------------------------
spring:
  profiles:
    active: dev
  http:
      converters:
        preferred-json-mapper: fastjson
      multipart:
        max-request-size: 512MB #最大请求大小
        max-file-size: 512MB #最大文件大小
  druid:
    #配置druid连接池
    datasource:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  mybatis:
    mapperLocations: classpath*:mapper/*-mapper.xml
    typeAliasesPackage: com.syfri.digitalplan
    basePackage: com.syfri.digitalplan.dao
    configuration:
      cacheEnabled: false
      lazyLoadingEnabled: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 10.119.119.233
    port: 6379
#------------------------------------------------------------
#pagehelper分页插件设置
pagehelper:
  helper-dialect: oracle
  reasonable: true
  support-methods-arguments: true
  row-bounds-with-count: true
  auto-dialect: true
#------------------------------------------------------------
#logging:
#  level: debug
logging:
  level.root: info
  level.com.syfri: debug
  path: logs/
  file: digitalplan.log
#------------------------------------------------------------
#swagger:
#  title: springboot
#  description: springboot swagger
#  version: 1.0
#  license: 111
#  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
#  terms-of-service-url: https://github.com/dyc87112/spring-boot-starter-swagger
#  contact:
#    email: xxx@syfri.cn
#    name: lx
#    url: http://blog.didispace.com
#  base-package: com.syfri
#------------------------------------------------------------


  ##########################################################
  ###################  开发环境的profile  ###################
  ##########################################################
---
spring:
  profiles: dev
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.119.119.205:1521/SZHYAGLDB
      username: SZHYAGLBJ
      password: SZHYAGLBJ
  ##########################################################
  ###################  正式环境的profile  ###################
  ##########################################################
---
spring:
  profiles: produce
  druid:
    #配置druid连接池
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.119.101.84:1521/SZHYAGLDB
      username: SZHYAGL
      password: SZHYAGL